included:
  - Inkdue/Inkdue

excluded:
  - Inkdue/Inkdue/Assets.xcassets

opt_in_rules:
  - empty_count
  - empty_string
  - first_where
  - explicit_init

disabled_rules:
  - todo

line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 700

type_body_length:
  warning: 300
  error: 400

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 40
  excluded:
    - id
    - x
    - y
    - z

reporter: "xcode"
